openapi: 3.0.0
info:
  x-skaffolder-id-project: 5cce0c40e3f2a35ef6dd30fd
  title: Manage_Film_Example
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      summary: Login API
      security: [] # No security
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example: # Sample object
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      summary: Verify token API
      security: [] #No security
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK

  #-----  Actor  -----
  /actor/:
    post:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd312c
      x-skaffolder-name-api: create
      x-resource: Actor
      summary: CRUD ACTION create
      tags:
        - Actor
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Actor"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                birthDate:
                  type: integer
                name:
                  type: string
                surname:
                  type: string
    get:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3133
      x-skaffolder-name-api: list
      x-resource: Actor
      summary: CRUD ACTION list
      tags:
        - Actor
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Actor"

  /actor/{id}:
    delete:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3134
      x-skaffolder-name-api: delete
      x-resource: Actor
      summary: CRUD ACTION delete
      tags:
        - Actor
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd312d
      x-skaffolder-name-api: get
      x-resource: Actor
      summary: CRUD ACTION get
      tags:
        - Actor
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Actor"
    post:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd312b
      x-skaffolder-name-api: update
      x-resource: Actor
      summary: CRUD ACTION update
      tags:
        - Actor
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Actor"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Actor"

  #-----  Film  -----
  /film/:
    post:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3145
      x-skaffolder-name-api: create
      x-resource: Film
      summary: CRUD ACTION create
      tags:
        - Film
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                genre:
                  type: string
                title:
                  type: string
                year:
                  type: number
    get:
      x-skaffolder-id-api: 5cce0c42e3f2a35ef6dd3149
      x-skaffolder-name-api: list
      x-resource: Film
      summary: CRUD ACTION list
      tags:
        - Film
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Film"

  /film/{id}:
    delete:
      x-skaffolder-id-api: 5cce0c42e3f2a35ef6dd314a
      x-skaffolder-name-api: delete
      x-resource: Film
      summary: CRUD ACTION delete
      tags:
        - Film
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3143
      x-skaffolder-name-api: get
      x-resource: Film
      summary: CRUD ACTION get
      tags:
        - Film
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
    post:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3146
      x-skaffolder-name-api: update
      x-resource: Film
      summary: CRUD ACTION update
      tags:
        - Film
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Film"

  /film/findBycast/{key}:
    get:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3130
      x-skaffolder-name-api: findBycast
      x-resource: Film
      summary: CRUD ACTION findBycast
      tags:
        - Film
      parameters:
        - name: key
          in: path
          description: Id della risorsa cast da cercare
          required: true
          schema:
            type: Objectid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Film"

  /film/findByfilmMaker/{key}:
    get:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd313c
      x-skaffolder-name-api: findByfilmMaker
      x-resource: Film
      summary: CRUD ACTION findByfilmMaker
      tags:
        - Film
      parameters:
        - name: key
          in: path
          description: Id della risorsa filmMaker da cercare
          required: true
          schema:
            type: Objectid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Film"

  #-----  FilmMaker  -----
  /filmmaker/:
    post:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3139
      x-skaffolder-name-api: create
      x-resource: FilmMaker
      summary: CRUD ACTION create
      tags:
        - FilmMaker
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FilmMaker"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
    get:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd313f
      x-skaffolder-name-api: list
      x-resource: FilmMaker
      summary: CRUD ACTION list
      tags:
        - FilmMaker
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FilmMaker"

  /filmmaker/{id}:
    delete:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3140
      x-skaffolder-name-api: delete
      x-resource: FilmMaker
      summary: CRUD ACTION delete
      tags:
        - FilmMaker
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd3137
      x-skaffolder-name-api: get
      x-resource: FilmMaker
      summary: CRUD ACTION get
      tags:
        - FilmMaker
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FilmMaker"
    post:
      x-skaffolder-id-api: 5cce0c41e3f2a35ef6dd313a
      x-skaffolder-name-api: update
      x-resource: FilmMaker
      summary: CRUD ACTION update
      tags:
        - FilmMaker
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FilmMaker"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FilmMaker"

  #-----  User  -----
  /user/{id}/changePassword:
    post:
      x-skaffolder-id-api: 5cce0c40e3f2a35ef6dd310f
      x-skaffolder-name-api: changePassword
      x-resource: User
      summary: Change password of user from admin
      tags:
        - User
      responses:
        "200":
          description: OK

  /user/:
    post:
      x-skaffolder-id-api: 5cce0c40e3f2a35ef6dd3110
      x-skaffolder-name-api: create
      x-resource: User
      summary: CRUD ACTION create
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                name:
                  type: string
                password:
                  type: string
                roles:
                  type: string
                surname:
                  type: string
                username:
                  type: string
    get:
      x-skaffolder-id-api: 5cce0c40e3f2a35ef6dd310c
      x-skaffolder-name-api: list
      x-resource: User
      summary: CRUD ACTION list
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /user/{id}:
    delete:
      x-skaffolder-id-api: 5cce0c40e3f2a35ef6dd310b
      x-skaffolder-name-api: delete
      x-resource: User
      summary: CRUD ACTION delete
      tags:
        - User
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id-api: 5cce0c40e3f2a35ef6dd3111
      x-skaffolder-name-api: get
      x-resource: User
      summary: CRUD ACTION get
      tags:
        - User
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      x-skaffolder-id-api: 5cce0c40e3f2a35ef6dd310a
      x-skaffolder-name-api: update
      x-resource: User
      summary: CRUD ACTION update
      tags:
        - User
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

# JWT security
security:
  - bearerAuth: []

# Components
components:
  # Security
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes

  # Data Model
  schemas:
    Actor:
      x-skaffolder-id-model: 5cce0c40e3f2a35ef6dd3117
      x-skaffolder-id-db: 5cce0c40e3f2a35ef6dd30fe
      properties:
        _id:
          type: string
        birthDate:
          type: integer
        name:
          type: string
        surname:
          type: string
      required:
        - _id
        - name

    Film:
      x-skaffolder-id-model: 5cce0c41e3f2a35ef6dd3128
      x-skaffolder-id-db: 5cce0c40e3f2a35ef6dd30fe
      properties:
        _id:
          type: string
        genre:
          type: string
        title:
          type: string
        year:
          type: number
      required:
        - _id
        - title

    FilmMaker:
      x-skaffolder-id-model: 5cce0c41e3f2a35ef6dd311c
      x-skaffolder-id-db: 5cce0c40e3f2a35ef6dd30fe
      properties:
        _id:
          type: string
        name:
          type: string
        surname:
          type: string
      required:
        - _id
        - name

    User:
      x-skaffolder-id-model: 5cce0c40e3f2a35ef6dd3107
      x-skaffolder-id-db: 5cce0c40e3f2a35ef6dd30fe
      properties:
        _id:
          type: string
        mail:
          type: string
        name:
          type: string
        password:
          type: string
        roles:
          type: string
        surname:
          type: string
        username:
          type: string
      required:
        - _id
        - password
        - username

  # Databases
  x-skaffolder-db:
    - x-id: 5cce0c40e3f2a35ef6dd30fe
      x-name: Manage_Film_Example_db

  # Pages
  x-skaffolder-page:
    - x-id: 5cce0c41e3f2a35ef6dd312a
      x-name: ActorEdit
    - x-id: 5cce0c41e3f2a35ef6dd3132
      x-name: ActorList
    - x-id: 5cce0c41e3f2a35ef6dd3142
      x-name: FilmEdit
    - x-id: 5cce0c42e3f2a35ef6dd3148
      x-name: FilmList
    - x-id: 5cce0c41e3f2a35ef6dd3136
      x-name: FilmMakerEdit
    - x-id: 5cce0c41e3f2a35ef6dd313e
      x-name: FilmMakerList
    - x-id: 5cce0c40e3f2a35ef6dd3106
      x-name: Home
